### ISSUE TITLE
Image Gadget Editor Improvements

### ISSUE THREAD

**Issue by dyoder** [dashkite/sansa#40]
- [x] Decrease description size
- [x] Increase the size of the preview
- [x] Increase the size of the selection window
- [x] Collapse URL and browse top-level menu
